### ISSUE TITLE
can we make glfwInit optional?

### ISSUE THREAD

**Issue by timotheecour** [libmir/dcv#105]
can we make glfwInit optional?
use case: when glfwInit fails  (eg on hosts where we can't have valid X server connection )

```
??:? void dcv.plot.figure._staticCtor1() [0x2e9eb708]
??:? void dcv.plot.figure.__modctor() [0x2e9eb7c0]
??:? void rt.minfo.__T14runModuleFuncsS482rt5minfo11ModuleGroup11runTlsCtorsMFZ9__lambda1Z.runModuleFuncs(const(immutable(object.ModuleInfo)*)[]) [0x560096]
??:? void rt.minfo.ModuleGroup.runTlsCtors() [0x55fd80]
??:? int rt.minfo.rt_moduleTlsCtor().__foreachbody1(ref rt.sections_elf_shared.DSO) [0x4fbbeb]
??:? int rt.sections_elf_shared.DSO.opApply(scope int delegate(ref rt.sections_elf_shared.DSO)) [0x4fc07d]
??:? rt_moduleTlsCtor [0x4fbbd4]
??:? rt_init [0x4f5caf]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x4f60e5]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x4f608b]
??:? _d_run_main [0x4f5fef]
```

**Comment by ljubobratovicrelja** [comment]
> (eg on hosts where we can't have valid X server connection )

I believe in that case you wouldn't need dcv:plot module at all, right? If that is so, you could just link against dcv:core and dcv:io. Would that do?

**Comment by timotheecour** [comment]
sorry, that's just not a good solution, suppose you have some complex code that is intended to work both with and without plotting depending on platform / architecture support. Inserting `static if(has_gl)` or `version(with_gl)` everywhere is too much trouble for client code.
Instead, we should allow runtime loading on demand via dlopen+friends of C shared libraries as done in other projects. I can provide references if needed.

Side question: is there a simple way to get `libgl` on ubuntu?

**Comment by ljubobratovicrelja** [comment]
I'm sorry, I'm not sure I understand the situation completely. But if you've encountered this in a production-like environment, than it is clear this should be done. So, how do we do this? What do we do with the rest of the `dcv.plot` code in runtime if `glfwInit` fails?

**Comment by ljubobratovicrelja** [comment]
> What do we do with the rest of the dcv.plot code in runtime if glfwInit fails?

(thinking out loud here) We could throw an exception at any call that depends on glfwInit?

**Comment by timotheecour** [comment]
Exactly. Currently, it wont even allow code imports plotting but doesnt call plotting functions. With this, it will allow importing such code and all is fine so long plotting isnt used.

**Comment by ljubobratovicrelja** [comment]
Awesome. @9il I believe we're OK with throwing Exceptions in the dcv.plot module. This is definitely a higher-level module with no (or very little) performant-critical code inside. Do you agree with this solution, or do you have some other proposition to solve it?

**Comment by ljubobratovicrelja** [comment]
> Side question: is there a simple way to get libgl on ubuntu?

Sorry for ignoring this, didn't catch it before. Do you mean glfw? If so `sudo apt-get install glfw3` will do, I think.

**Comment by timotheecour** [comment]
No, libgl. Theres a recursive dub dependency on libgl (maybe after brew install ffmpeg, i forgot where it arose from)

**Comment by ljubobratovicrelja** [comment]
Isn't libGL.so present by default? I believe even unity depends on it :). Anyhow, if you're failing to link against it, maybe it's not named the way [dcv's dub.json](https://github.com/libmir/dcv/blob/master/dub.json#L90) expects it. Sorry, I'm not much of a help here, since I don't have ubuntu machine. Hope you'll manage.

**Comment by timotheecour** [comment]
That's another point: linker is case sensitive and libGL may be present but dub.json specifies libgl

**Comment by timotheecour** [comment]
Supporting Ubuntu would be great, given its popularity... parallels or virtualbox are pretty easy to setup :)

**Comment by 9il** [comment]
> Awesome. @9il I believe we're OK with throwing Exceptions in the dcv.plot module. This is definitely a higher-level module with no (or very little) performant-critical code inside. Do you agree with this solution, or do you have some other proposition to solve it?

Agreed

**Comment by 9il** [comment]
#109

**Comment by ljubobratovicrelja** [comment]
> Agreed

Awesome! @timotheecour I'll try fix this by the end of the day.

**Comment by ljubobratovicrelja** [comment]
> That's another point: linker is case sensitive and libGL may be present but dub.json specifies libgl

What's really interesting is that I've developed much of dcv on ubuntu. And that `gl` linking that was put there in dub.json seemed to be working. :) Anyhow, hope your linking is fine after Ilya's fix. And thanks for pointing this out!

**Comment by timotheecour** [comment]
tracked in https://github.com/libmir/dcv/pull/113 so closing this
