### ISSUE TITLE
plotting without X-server

### ISSUE THREAD

**Issue by timotheecour** [libmir/dcv#114]
related to https://stackoverflow.com/questions/4931376/generating-matplotlib-graphs-without-a-running-x-server

matplotlib (and ggplotd) allow drawing graphs without an X-server running (or when X-server would be too slow, eg on a network)

would be nice to allow configuring the backend, just as is done in matplotlib.
Also, putting things in `static this` isn't the most flexible in case user wants to set the backend based on custom logic; how about at the very least having a version(dcv_disable_static_glfwinit) which will disable the `static this` call to glfwInit and let the user call whatever's inside that `static this` manually; he can select the backend here.

* all plotting code would probably be best put in a separate git repo

* would be nice to have an abstraction layer that allows swapping in different plotting backends (eg with or without X-server, and also with alternatives to ggplotd) while allowing client code to use same API's. 

* I've had good experience with plotting images in D using SFML (i had used SWIG bindings but there's also https://code.dlang.org/packages/dsfml) ; eg allows direct and fast opengl drawing including animations with high FPS. Curious what are your thoughts on this and how it would compare to current option (eg in terms of flexibility of using arbitrary opengl, speed etc)

**Comment by ljubobratovicrelja** [comment]
This sounds awesome, but it also sounds like a lot of work for dcv. But anyway, I agree it should be done.
