### ISSUE TITLE
simplify API's with isSlice

### ISSUE THREAD

**Issue by timotheecour** [libmir/dcv#115]
here's an example:
```
Figure plot(SliceKind kind, size_t[] packs, Iterator) (Slice!(kind, packs, Iterator) slice, GGPlotD gg, string title = "");
```

could be simplified (and be more readable) with:

```
Figure plot(S)(S slice, GGPlotD gg, string title = "") if(isSlice!S);
```

there are lots of such cases (search for SliceKind)

**Comment by 9il** [comment]
Why this should be simplified?

**Comment by timotheecour** [comment]
`Figure plot(S)(S slice, GGPlotD gg, string title = "") if(isSlice!S)`

is arguably more readable than

`Figure plot(SliceKind kind, size_t[] packs, Iterator) (Slice!(kind, packs, Iterator) slice, GGPlotD gg, string title = "")`

* shorter
* doesn't leak Slice internals
* hides all the logic inside the existing isSlice
* if Slice ever changes, it won't affect this function signature.

**Comment by 9il** [comment]
The older style should be used. After your change the following code would not work for example:

```d
    import mir.ndslice;
    const s = slice!double(2, 3);

    auto foo(SliceKind kind, size_t[] packs, Iterator) (Slice!(kind, packs, Iterator) slice)
    {
        slice.popFront;
    }

    foo(s);
```

**Comment by 9il** [comment]
I agree that (S) is simpler. But a DIP that strip `const` should be implemented first .

**Comment by timotheecour** [comment]
`isSlice` has a confusing name, isX should always be bool-return.

how about:
```
// before:
template isSlice(T) {
    static if (is(T : Slice!(kind, packs, Iterator), SliceKind kind, size_t[] packs, Iterator))
        enum size_t[] isSlice = packs[];
    else
        enum size_t[] isSlice = null;
}

// after: rename isSlice to getSlicePacks (and update code using it) and define:
template isSlice(T) {
    enum isSlice = is(T : Slice!(kind, packs, Iterator), SliceKind kind, size_t[] packs, Iterator));
}
```

would that be acceptable? at least as PR?

**Comment by 9il** [comment]
`isSlice` behaves as boolean if it is used as boolean. It just stores additional information that is very useful for generic code
