### ISSUE TITLE
is this library dead?

### ISSUE THREAD

**Issue by aferust** [libmir/dcv#129]
I have wanted to try my new [regionprops](https://github.com/aferust/regionpropsford) library with dcv. I could not even built dcv using dub + ldc2 (on both ubuntu and win10). It always complains about mir.algorithm no matter which version I use. Please say dcv is not dead. It would be awesome if we have something like opencv in dlang :(

**Comment by ljubobratovicrelja** [comment]
With a heavy heart, I have to say- yes, DCV project is dead.

For past few years I haven't had time (nor motivation to be honest) to continue the development. I'd be glad to pass the torch to anyone interested, though I doubt anyone would apply.

 Therefore you're much better of wrapping a subset of OpenCV, or continue using dlib.

**Comment by aferust** [comment]
Thank you for answering. Hope it continues someday somehow :/

**Comment by aferust** [comment]
I am playing around with it [here](https://github.com/aferust/dcvrev). There is a list of my contributions there. I can make a PR if it is welcome. I need your opinions on some subjects. The most important one is: 
Is ref-counted images a good idea?

https://github.com/aferust/dcvrev

**Comment by ljubobratovicrelja** [comment]
Hi @aferust. Happy to see you're using this, and your additions seem quite interesting!

Sounds like you're pretty serious around this, so if you want, please do present your changes as PRs and I'll do my best to review and accept them. However, I of course wouldn't take it against you if you want to keep doing your thing and keep things as a fork, and retain complete authority - I wouldn't really challenge you for changes, but if you do want to restructure things radically, it is surely better to keep it as a fork.

>Is ref-counted images a good idea?

What do you have in mind? Our [Image](https://github.com/libmir/dcv/blob/master/source/dcv/core/image.d#L96) objects have ref-counted internal memory (by simply using D dynamic arrays). Are you thinking we should not do this? Btw, we were meaning to remove Image class, as it was only meant to be a dynamic typed image container class, but for any manipulation we would be using slices.

**Comment by aferust** [comment]
Hi Relja,

I am planning to make a PR after resolving some issues with the new OpenGL support. Actually, there is only one reason for me to include the support for the modern OpenGL API. I couldn't overlay the primitives on texture using the legacy API :).
I have never used the old mir API. I am currently learning the new one. In the new one, there is no uninitializedSlice!T(image.shape);, I don't know how it used to allocate the data. I had to change these allocations to makeUninitSlice!T(GCAllocator.instance, image.shape);. That means Slice!T(T* ...) types are now GC allocated. I then discovered Slice!(RCI!T, ...) types which are ref-counted, I use those ref-counted slices and arrays (mir.rc) heavily in the new measure module. However, currently, most of the functions expect Slice!(T* ...). So, we have two different Iterator templates now (T* and RCI!T). I modified some implementations to accept both. But, It needs more modifications so that those Iterators can work together. Or I can change all of my new implementations to use Slice!(T* ...) though. But, I liked the idea of  RCI!T iterator, since I can make functions @nogc nothrow. It would be awesome if something like makeUninitSlice!T(RCAllocator.instance, image.shape) exists.

I see that the Image class is currently only used for IO and displaying purposes currently. I don't have a serious problem with it. so far.

There are currently some issues that cannot be resolved in a decent time. 
1) The multi-vision module cannot be compiled due to some API changes in mir.algorithm. This may need some touch of the author of it, Henry Gouk.
2) There is a linker/compiler bug that made me disable the parallel foreach in the calcGradients function. That's what Ilya says: https://forum.dlang.org/post/nlfjtdldgpburarpmtkk@forum.dlang.org

Do you expect those two resolved before my PR? As I said, I cannot resolve these two in a decent time.

Best regards.

**Comment by ljubobratovicrelja** [comment]
So sorry for the radio silence - first it was the holidays that kind of took me from responding, as I wasn't near to my PC and its always tedious to respond via cell to any serious message, and later on I honestly had trouble understanding your message. It's perfectly well put, but I am just that out of shape with D. :/

> Do you expect those two resolved before my PR? As I said, I cannot resolve these two in a decent time.

I honestly would have to get reacquainted with D, Mir, and even DCV before answering, which is highly unlikely. Also, please consider the fact that this library has never taken of - nobody is using it actively, except from a few enthusiasts and hobbyists like ourselves. Therefore, with very scarce free time in a day, I find it really hard to invest any time into the development of this library. In your place, I would rather bet on C/C++/D interoperability libraries to have evolved so much to enable you to more easily use OpenCV within D. I know Mir API is neat and to me personally that was the reason and motivation to go for implementing a vanilla D computer vision library, but it just isn't feasible, unless you have a strong community - it's way too much work.

That said, if you yourself are still willing to put in work, ping Henry and Ilya for support, please go ahead. I can give you support on code revision, but I personally wouldn't be able to work on the code itself, sorry.

**Comment by aferust** [comment]
Thanks for your response. I understand your situation. I am also doing this for hobby purposes. I created an [OpenCV](https://github.com/aferust/opencvd) binding ( using C wrappers) 3 years ago, and I am maintaining it, although I am not checking API changes very frequently.  Ok, I am making a PR for you to review. Please have your time and don't be in a rush.
