### ISSUE TITLE
ImageFormat dependency has issues with some jpg??

### ISSUE THREAD

**Issue by infinityplusb** [libmir/dcv#169]
I am using DCV to read images in (which might be overkill for the moment, but I intend to do more ... eventually).

However reading in an image like
![helmet](https://github.com/libmir/dcv/assets/7320655/251c913e-14d3-4af5-82e5-c44d810cd698)

throws an error through ImageFormat

```
imageformats.ImageIOException@/../.dub/packages/imageformats/7.0.2/imageformats/imageformats/jpeg.d(236): invalid / unsupported marker
----------------
../.dub/packages/imageformats/7.0.2/imageformats/imageformats/jpeg.d:236 [0x55eb4fc4b332]
../.dub/packages/imageformats/7.0.2/imageformats/imageformats/jpeg.d:104 [0x55eb4fc4a837]
../.dub/packages/imageformats/7.0.2/imageformats/imageformats/package.d:115 [0x55eb4fc38cd1]
../.dub/packages/imageformats/7.0.2/imageformats/imageformats/package.d:49 [0x55eb4fc38c03]
../.dub/packages/dcv/0.3.0/dcv/source/dcv/imageio/image.d:353 [0x55eb4fc36b4b]
../.dub/packages/dcv/0.3.0/dcv/source/dcv/imageio/image.d:93 [0x55eb4fc36a8c]
../ImmersiveDataAnalysis/source/vulkan/textureImage.d:19 [0x55eb4fbbc585]
../ImmersiveDataAnalysis/source/vulkan/vulkan.d:26 [0x55eb4fbb99d7]
../ImmersiveDataAnalysis/source/application.d:178 [0x55eb4fbc33fe]
../ImmersiveDataAnalysis/source/immersivedataanalytics.d:42 [0x55eb4fbc337a]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x7f72bdd9f3bb]
??:? _d_run_main2 [0x7f72bdd9f1d5]
??:? _d_run_main [0x7f72bdd9f02d]
usr/lib/ldc/x86_64-linux-gnu/include/d/core/internal/entrypoint.d:42 main [0x55eb4fbc3751]
??:? [0x7f72bcc280cf]
??:? __libc_start_main [0x7f72bcc28188]
??:? [0x55eb4fbb2ba4]
Error Program exited with code 1
```

switching the image to another jpg works, so not sure what is specific about this particular image.

**Comment by ljubobratovicrelja** [comment]
The error actually comes from imageformats library, namely seems like a [type of encoding that was not supported](https://github.com/tjhann/imageformats/blob/master/imageformats/jpeg.d#L236
). As you can see [here](https://www.disktuna.com/list-of-jpeg-markers/) many of existing markers aren't supported.

Given imageformats project is discontinued, I guess solution to enable these kinds of JPEG is not trivial for this project as well. Therefore, I can only say to maybe re-save this image through paint or gimp, maybe it would work in that case.

**Comment by aferust** [comment]
Hi, thank you for reporting this. It has been some time, but I remember that I switched to gamut for image file IO with DCV (imageformats is no longer used). Are you sure that you are using ~master branch? Please don't use the library from dub registry since it is not up-to-date.

**Comment by aferust** [comment]
The lib imageformats is no longer used
