### ISSUE TITLE
migration to ndslice.algorithm and Mir

### ISSUE THREAD

**Issue by 9il** [libmir/dcv#20]
The common pattern for dcv is `aSlice.byElement.rangedFunction`. It has few performance issues:
1. It can not be vectroized
2. It requires additional computations because range interface

So, you may want to swtich from `dcv.core.algorithm` to `ndslice.algorithm`. 

The documentation for `ndslice.algorithm` can be found [here](docs.mir.dlang.io/latest/mir_ndslice_algorithm.html). `ndslice.algorithm` is currently available only in Mir.

So, switching to Mir is good option. It is providing recent and upcoming ndslice changes for both DMD and LDC. Also, mir will migrate to Phobos's ndslice after 2-3 DMD releases and will provide deprecation imports with aliasing. `ndslice,algorithm` is not the last module in ndslice package, also `ndslice.concatenation` will be added this year.

Please ask me questions if you have any.

**Comment by ljubobratovicrelja** [comment]
> So, you may want to swtich from dcv.core.algorithm to ndslice.algorithm.

That was definitely my plan! 

> So, switching to Mir is good option

I agree. I've tracked ndslice.algorithm development, and I've also drawn that conclusion.

> Please ask me questions if you have any.

Thanks for all the help and support here! Really appreciate it!

**Comment by 9il** [comment]
I think this can be done step by step. First step is just to migrate to mir without new code. Then I would be able to help to port algorithm to ndslice.algorithm

**Comment by ljubobratovicrelja** [comment]
I agree. I'll make this a top priority task. I'll branch-out and start working as soon as I get some spare time. I suppose it would be ok to ping you for review before merge?

**Comment by 9il** [comment]
Yes, thanks!

**Comment by 9il** [comment]
https://github.com/libmir/mir/blob/master/README.md notes DCV too :-)

**Comment by ljubobratovicrelja** [comment]
Awesome, thanks! Hope many more items will join that list in future! :)
