### ISSUE TITLE
The site is broken on android

### ISSUE THREAD

**Issue by 9il** [libmir/dcv#21]
_the site is broken on android, it constantly just redirects to itself_
from https://twitter.com/WebFreak001/status/765138108417474560

**Comment by ljubobratovicrelja** [comment]
I'm aware of this. Haven't had time to tend to it. It only occurs on android AOSP browser. On chrome, firefox and other popular browsers it works properly, so it's hard to debug.

**Comment by ljubobratovicrelja** [comment]
And thanks for redirecting the issue here!

**Comment by ljubobratovicrelja** [comment]
This should be fixed with newest updates on website. It works fine on my android browser (content formatting is bit off, but that's another issue). I'll wait few days for testing until closing the issue.

**Comment by ljubobratovicrelja** [comment]
I pretty sure this problem does not exist anymore. If anyone notices differently, please reopen the issue. Closing for now.
