### ISSUE TITLE
Support 32 bit compilation

### ISSUE THREAD

**Issue by ljubobratovicrelja** [libmir/dcv#22]
- As noted in #19 ulong is used for size type, which should be fixed. 
- Surely there's other stuff to be discovered that's brake 32bit compilation...

**Comment by 9il** [comment]
We need Travis test first

**Comment by ljubobratovicrelja** [comment]
Adding travis will not be trivial, since x86 libs have to be build. Here I wanted to tend only to ulong vs size_t problem. I'd like to solve testing in separate PR.

**Comment by ljubobratovicrelja** [comment]
> I'd like to solve testing in separate PR.

That is why it's in separate issue #19
