### ISSUE TITLE
Dub review

### ISSUE THREAD

**Issue by 9il** [libmir/dcv#26]
`dub.json` should not import examples, but in unittest configuration.
Also, according to the #25, dcv should not depend on C libraries. Mir will have matrix inversion: that will allow to exclude scid (C LAPACK) dependency.

**Comment by ljubobratovicrelja** [comment]
> dub.json should not import examples, but in unittest configuration.

OK, I'll fix that.

> Mir will have matrix inversion: that will allow to exclude scid (C LAPACK) dependency.

That's great!
