### ISSUE TITLE
Parallelisation should be optional

### ISSUE THREAD

**Issue by 9il** [libmir/dcv#28]

**Comment by ljubobratovicrelja** [comment]
@DmitryOlshansky also stated this.

And if I remember correctly, @DmitryOlshansky you suggested that we make a thread count a template parameter, where default value would be to use all cores? I believe this would make a good design.

**Comment by 9il** [comment]
Thread count is runtime value and there are no reason to make it compile time. Furthermore, instead of passing thread count, passing TaskPool is much preferable.

Compile time (template) argument may be used to determine if the code use or does not use `std.parallelism`.

**Comment by DmitryOlshansky** [comment]
> And if I remember correctly, @DmitryOlshansky you suggested that we make a thread count a template parameter,

I was arguing for run-time parameter, of course.

**Comment by ljubobratovicrelja** [comment]
> I was arguing for run-time parameter, of course.

Thank you Dmitry! Sorry, I  misunderstood you, and obviously didn't think it through.

> Thread count is runtime value and there are no reason to make it compile time. Furthermore, instead of passing thread count, passing TaskPool is much preferable.

Sounds good, thanks for pointing that out!

**Comment by DmitryOlshansky** [comment]
> Furthermore, instead of passing thread count, passing TaskPool is much preferable.

What would be a TaskPool for the serial version?

**Comment by 9il** [comment]
@DmitryOlshansky I am sorry, but I don't know about the  _serial version_. What is it?

**Comment by DmitryOlshansky** [comment]
> out the serial version. What is it?

Single threaded hope that's clear.

**Comment by 9il** [comment]
> Furthermore, instead of passing thread count, passing TaskPool is much preferable.
> What would be a TaskPool for the serial version?

Just taskpool with zero additional threads. It is valid

**Comment by 9il** [comment]
#53
