### ISSUE TITLE
dcv.dlang.io

### ISSUE THREAD

**Issue by 9il** [libmir/dcv#30]
@ljubobratovicrelja You may want to ask @wilzbach to move DCV site :-)

**Comment by ljubobratovicrelja** [comment]
Awesome! :) @wilzbach can this be done, and how?

**Comment by wilzbach** [comment]
> @ljubobratovicrelja You may want to ask @wilzbach to move DCV site :-)

See the docs: https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/

You should be able to directly enter your domain here:

![image](https://cloud.githubusercontent.com/assets/4370550/17839402/e7a7a706-67e6-11e6-894d-ab19793d29b5.png)

At least from my side, you should be ready to rock:

```
> dig dcv.dlang.io

; <<>> DiG 9.10.4-P2 <<>> dcv.dlang.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21516
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1024
;; QUESTION SECTION:
;dcv.dlang.io.          IN  A

;; ANSWER SECTION:
dcv.dlang.io.       1798    IN  CNAME   ljubobratovicrelja.github.io.
ljubobratovicrelja.github.io. 3599 IN   CNAME   github.map.fastly.net.
github.map.fastly.net.  2718    IN  CNAME   prod.github.map.fastlylb.net.
prod.github.map.fastlylb.net. 900 IN    A   151.101.36.133

;; Query time: 85 msec
;; SERVER: 127.0.0.3#53(127.0.0.3)
;; WHEN: Sun Aug 21 21:32:25 CEST 2016
;; MSG SIZE  rcvd: 171
```

**Comment by ljubobratovicrelja** [comment]
Great! - Thank you guys!

**Comment by ljubobratovicrelja** [comment]
Done! :) - [dcv.dlang.io](http://dcv.dlang.io/)

**Comment by 9il** [comment]
Great)
