### ISSUE TITLE
norm and asType can be deprecated.

### ISSUE THREAD

**Issue by 9il** [libmir/dcv#35]
Both are single line functions. See #33 
`normalized` single line too.
`scaled` is not used if am not wrong. User can do `slice[] *= scalar`/`slice[] += scalar` or use `ndEach` if both `*` and `+` are required.

**Comment by ljubobratovicrelja** [comment]
As noted in #33 norm should definitely be deprecated. Although my original intention is to have an analogue to [numpy.linalg.norm](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html). Should something like that  exist one day in some higher layers of Mir?

Normalized should be definitely removed - I wanted to have this as convenience function, but now I believe it only bloats the API.

Regarding the `asType`, even thought it's a one-liner (and its trivial to achieve with mapping), I really like this concept to exist in a separated function. IMHO it is too often used to be replaced with its current implementation in user code (`inslice.ndMap!(a => cast(O)a).slice` vs `inslice.asType!O`). Not only it is easier to write, I believe it is far easier to read when understanding someone's algorithm. Again, my goal here was to have similar API to [numpy.ndarray.astype](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html). But maybe that's just me not accustomed enough to functional concepts, and liking to have everything as a named function. For now, I'd like not to deprecate it, but we can discuss it again latter. Sounds fair?

Same story with `scaled`. This is fairly trivial concept and (as you state) can be easily replaced using ndEach (as it is implemented currently) or array ops in user code. But then again, it is often used when switching bit depth in images (going from 16bit to 8bit, one should call `image.scaled(65535 / 255)`), so I wanted to have it for easier write/read. I'm only explaining my motivation for this function, but here I'm leaning more towards deprecating it (especially now that we got ndEach and ndMap as easy and elegant replacement for these functions). Here I'm voting for deprecation, if anyone thinks different, let us know.

So, recap:
- norm: deprecate
- normalized: deprecate
- asType: let's not deprecate for now
- scaled: deprecate

... and remove soon enough. Library is young, and API will obviously evolve more, so I think there's no need for deprecate ones to linger.

Please tell me what you think.

**Comment by 9il** [comment]
> Should something like that exist one day in some higher layers of Mir?

Yes, see https://github.com/libmir/mir/issues/327.

> For now, I'd like not to deprecate it, but we can discuss it again latter. Sounds fair?

Lets retain it for now. It can be deprecated after https://github.com/libmir/mir/issues/339 be released.

**Comment by ljubobratovicrelja** [comment]
> Yes, see libmir/mir#327.

Cool! That's it!

> Lets retain it for now. It can be deprecated after libmir/mir#339 be released.

Awesome! This is truly needed feature for ndslice.

**Comment by 9il** [comment]
@ljubobratovicrelja lazy `as` PR was opened https://github.com/dlang/phobos/pull/4825

**Comment by 9il** [comment]
@ljubobratovicrelja `as` was added to the `mir.ndslice.slice`. It is laze. You can use `sl.as!float.slice` chain instead of `sl.asType!float`.

**Comment by ljubobratovicrelja** [comment]
Awesome. Working on it in #60.
