### ISSUE TITLE
Canny

### ISSUE THREAD

**Issue by ljubobratovicrelja** [libmir/dcv#4]
Non-maxima suppression implementation is faulty.

See RHT example canny image:
https://github.com/ljubobratovicrelja/dcv/blob/master/examples/rht/result/canny.png

**Comment by ljubobratovicrelja** [comment]
Seems fixed with b44e4a81cecc75595126d355736f846a75058a5c.

With following code:

``` d
#!/usr/bin/env dub
/+ dub.sdl:
    name "cannytest"
    dependency "dcv" path="path/to/dcv"
+/

import std.stdio;
import dcv.core, dcv.io, dcv.imgproc, dcv.plot.figure;

void main()
{
    Image image = imread("dcv/examples/data/img.png");

    image
        .sliced
        .asType!float[0..$, 0..$, 1]
        .conv(gaussian!float(0.84f, 3, 3))
        .canny!ubyte(100)
        .imshow;

    waitKey();

}
```

I get following result:

![canny](https://dl.dropboxusercontent.com/u/86832490/canny.png)

Here is the OpenCV's result with similar setup:
![opencv_canny](https://dl.dropboxusercontent.com/u/86832490/canny_opencv.png)

@DmitryOlshansky, looking at opencv's result, seems like algorithm would probably need another revision, but do you agree to call it "OK", and close it for now? Non-maxima suppression can be tweaked to achieve better results, but it would take me more time, which I'd like to invest in other issues at this moment.

**Comment by DmitryOlshansky** [comment]
Yeah, looks much better:)

**Comment by ljubobratovicrelja** [comment]
Awesome, tnx! Will update canny images in RHT example asap.
