### ISSUE TITLE
ggplot dependency should be optional and only for figure drawing

### ISSUE THREAD

**Issue by 9il** [libmir/dcv#47]
glfw can be used for imshow directly

**Comment by ljubobratovicrelja** [comment]
> glfw can be used for imshow directly

It is used directly. ggplotd is used only to draw plots on the figure canvas. 

I propose we deal with this in the same instance as #25. Looking at the vibe.d project as example, I think having library separated to subPackages [as there](https://github.com/rejectedsoftware/vibe.d/blob/master/dub.sdl) would be a good choice. If we have visualization as separated subPackage, having ggplotd as optional utility though separate configuration seems ok. 

Thoughts?

**Comment by 9il** [comment]
Looks OK. I am not sure about dub bugs. But idea is good
