### ISSUE TITLE
uninitializedSlice 

### ISSUE THREAD

**Issue by 9il** [libmir/dcv#51]
https://github.com/dlang/phobos/pull/4780 will be available for 2.072. As soon as LDC will have it too, the code can be simplified.

**Comment by 9il** [comment]
all `sliced` calls can be replaced with `uninitializedSlice` or `slice`

**Comment by ljubobratovicrelja** [comment]
Yep, had this planned. :-)

**Comment by 9il** [comment]
Will note you when this be included to Mir

**Comment by ljubobratovicrelja** [comment]
Thank you!

**Comment by 9il** [comment]
@ljubobratovicrelja v0.18.0-beta0

**Comment by 9il** [comment]
http://docs.mir.dlang.io/latest/mir_ndslice_slice.html#.uninitializedSlice
and http://docs.mir.dlang.io/latest/mir_ndslice_slice.html#.makeUninitializedSlice

**Comment by aferust** [comment]
since API function is not using GC anymore, this issue is not relevant
