### ISSUE TITLE
Go forward with LLVM and drop DMD BE?

### ISSUE THREAD

**Issue by 9il** [libmir/dcv#52]
According to https://github.com/libmir/dcompute/issues/7 upcoming openCL can be used for thread and synchronization management instead of druntime for CPU (not only for GPUs) and kernels can be optimized as good as common CPU code. So the idea is to drop support for DMD. The benefits:
1. Do not need optimise DMD BE, currently it is 20 times slower for matrix multiplication comparing with LDC. In addition, @WalterBright has a lot of another work with DMD FE.
2. Simple, fast and `nothrow @nogc` parallellism using upcoming dcompute.
3. Code will be simplified.
4. Less maintaining efforts will be required.
5. Less uncertainty for users.

**Comment by 9il** [comment]
https://github.com/libmir/mir/pull/347

**Comment by bubnenkoff** [comment]
> BE is codegen?
> 
>  Am I right understand that LDC is use some parts from dmd like dmd FE?

**Comment by 9il** [comment]
> BE is codegen?
> Am I right understand that LDC is use some parts from dmd like dmd FE?

Yes, LDC is DMD FE + LLVM.

**Comment by wilzbach** [comment]
>  So the idea is to drop support for DMD. The benefits:

Let me play the devils advocate - some disadvantages that come to my mind:
- less dog-fooding for the DMD BE (well we can argue whether this is good or bad)
- loss of blazingly fast compilation times for testing / development
- makes it harder for additions to get into Phobos if they are never tested with the DMD BE
- risk of having to work with an older FE (in case LDC looses contributors/traction)
- in case the GDC backend ever catches up, we probably have lost support for it too
- in same environments like the DLang Tour there's only DMD installed atm

**Comment by 9il** [comment]
> less dog-fooding for the DMD BE (well we can argue whether this is good or bad)

Having our own compiler BE is over engineering. Go is more popular because it is more simple for users and compiler developers.

> loss of blazingly fast compilation times for testing / development

I think we can add special configuration for dub without code generation step.

> makes it harder for additions to get into Phobos if they are never tested with the DMD BE

GLAS would not be part of Phobos without default LDC compiler. Lets be realistic, one WB can not create fast BE as LLVM. We need 20 WBs at least.

> risk of having to work with an older FE (in case LDC looses contributors/traction)

D will die without LDC.

> in case the GDC backend ever catches up, we probably have lost support for it too

This is not problem. LDC is available for almost all Linux distrs.

> in same environments like the DLang Tour there's only DMD installed atm

10 minutes to fix it.

**Comment by 9il** [comment]
https://github.com/ldc-developers/ldc/issues/1778

**Comment by ljubobratovicrelja** [comment]
@9il I'll be honest here and say I'm not sure how I feel about this decision. I'm still new to D, so I can't tell if this is a smart decision for sure, but I have to say it feels accelerated too much (or maybe not, seems like you've been thinking about it for some time?). I understand all the pros you hold in favor of using only LDC, but I feel this will turn away quite few people. But then again, people who'll use our libraries will seek performance, and by that will most probably be already using LDC.

Mir not supporting DMD forces DCV to ditch it also. Alternative is not to be up-to-date with Mir, which I'd like even less, so I'll follow you on this one. Hope you're right.

**Comment by 9il** [comment]
https://github.com/libmir/mir/releases/tag/v0.18.0

**Comment by JohanEngelen** [comment]
@9il How about having DMD support, but with abysmal performance? Just very simple implementations of the functions, without any optimization. Such simplified implimentations may serve as extra documentation demonstrating the intent of the LDC optimized implementations. For new contributors, it's nice to look at simple code first to understand what a certain function is supposed to be doing.

**Comment by 9il** [comment]
@JohanEngelen The problem that DMD is default. Comparing  LDC AVX2 vs DMD SSE2, the last one is more then 50 times slower. Very slow code for first experience is a huge blocker for new users.

**Comment by 9il** [comment]
20 times is for LDC SSE2 vs DMD SSE2

**Comment by JohanEngelen** [comment]
Yeah, that's what I meant with abysmal performance. 1000x slower. Fine. :) 
But I also think that for many users having that much slower execution time means you cannot test anything serious with it anyway. I guess people want to use DMD for the fast compile time, but when your algorithm is 50x slower... that easily surpasses any compile speed gain.
