### ISSUE TITLE
Updated Mir version

### ISSUE THREAD

**Issue by ljubobratovicrelja** [libmir/dcv#54]
@9il [unit tests are failing](https://travis-ci.org/ljubobratovicrelja/dcv) - I'm not quite sure what has changed in `mir.ndslice.slice.slice`, could you help out?

**Comment by 9il** [comment]
looks like regression

**Comment by 9il** [comment]
will fix

**Comment by ljubobratovicrelja** [comment]
tnx!

**Comment by 9il** [comment]
v0.18.1

**Comment by ljubobratovicrelja** [comment]
Awesome, thank you!
