### ISSUE TITLE
deprecate error msg

### ISSUE THREAD

**Issue by 9il** [libmir/dcv#61]
`deprecate("pelase use 'yourSlice.as!aType.slice' instead")` for example

**Comment by ljubobratovicrelja** [comment]
Ah, cool tnx - will do!

**Comment by ljubobratovicrelja** [comment]
Hope 1fa65502db6d7eca1c426bfaee841cb3542f3f84 is OK? If you think so, I'll add similar message to other deprecated functions latter on, after merging #60.

**Comment by 9il** [comment]
> Hope 1fa6550 is OK?

Yes

**Comment by ljubobratovicrelja** [comment]
closed with #69
