### ISSUE TITLE
How the linear resizing is supposed to work?

### ISSUE THREAD

**Issue by georgy7** [libmir/dcv#72]
When I resize an image in GIMP, I got completely different result.
For example, in DCV I do this:

```
// w == 3; The image is a 2MP RGBA photo.

auto slice = image.sliced;
writeln(slice[0, 0, 0 .. $]);
auto thumbnail = slice.resize!linear([w, w]);
auto rgb = thumbnail[0 .. $, 0 .. $, 0 .. 3];
writeln(rgb);
```

and I got this:

```
[196, 198, 249, 255]
[[[196, 198, 249], [156, 166, 189], [82, 59, 100]], [[231, 163, 178], [35, 39, 34], [104, 98, 122]], [[141, 120, 119], [26, 36, 44], [169, 141, 130]]]
```

The first pixel of the downscaled image is the same as the first pixel of original image.
This is not what I expect.

**Comment by ljubobratovicrelja** [comment]
> The first pixel of the downscaled image is the same as the first pixel of original image.

Yes, the first and the last pixels remain the same as in input image, as shown in the [example](https://github.com/ljubobratovicrelja/dcv/tree/master/examples/imgmanip). 

> This is not what I expect.

Weighting for interpolation is completely in favor of the first element there. Should it be different? 

What did you expect?  Also, what did gimp give you?

**Comment by georgy7** [comment]
Thanks for your response.
I supposed, the first result pixel was the average value of the corresponding part of the source image (in downsampling case).
Now, I am confused. If the first pixel is the first pixel of the source image and the right-top pixel is the right-top pixel of the source image, then, what is the middle-top pixel? The average value of the whole row except for the first and the last pixels?

**Comment by ljubobratovicrelja** [comment]
That would be some another interpolation scheme. You can see how bilinear implementation works [here](https://en.m.wikipedia.org/wiki/Bilinear_interpolation).  Sorry I'm not able to give you more elaborated example at the moment, hope you can understand it from Wikipedia. Also, you can take a look at the  [2d resizing](https://github.com/ljubobratovicrelja/dcv/blob/master/source/dcv/imgproc/imgmanip.d#L522),  and [bilinear interpolation](https://github.com/ljubobratovicrelja/dcv/blob/master/source/dcv/imgproc/interpolate.d#L135)  source code. It's not too complicated to understand.

**Comment by georgy7** [comment]
Ok, thanks.
