### ISSUE TITLE
[question] Migration to libmir

### ISSUE THREAD

**Issue by 9il** [libmir/dcv#82]
@ljubobratovicrelja Are you interesting to move DCV to libmir project? Copyright, the project name are preserved as is.

**Comment by ljubobratovicrelja** [comment]
Yes I've been thinking about it. I'm not completely sure what would be pros and cons in this. By proc, I can see enhanced library visibility and support, and by cons I'm not seeing one at the moment.

I was thinking of making a dcv organization in near future, but maybe it's more logical to just join it with mir org. Please let me think about this for few days.

In the meantime, could you maybe tell me your point of view - why do you think it would be good for dcv to move it to libmir?

**Comment by 9il** [comment]
> In the meantime, could you maybe tell me your point of view - why do you think it would be good for dcv to move it to libmir?

Computer vision is very close to machine learning. I am interesting to consolidate more people around Mir / ndslice. We need active Mir community and developers to be good looking for companies. Also I am thinking that after few years of evaluation we can make an API review and rework for DCV to make it more low level and user friendly. Doing this will help to use DCV as a backend instead of OpenCV.

**Comment by ljubobratovicrelja** [comment]
> Computer vision is very close to machine learning

True. But IMHO if we're joining dcv (and other libraries like it) to libmir, maybe the goal of libmir organization should be refactored to focus on more general scientific computing rather than only machine learning. Don't you agree?

> I am interesting to consolidate more people around Mir / ndslice. We need active Mir community and developers to be good looking for companies.

This sounds really good. I'd be interested in backing this plan up.

> Also I am thinking that after few years of evaluation we can make an API review and rework for DCV to make it more low level and user friendly.

Yes, I would like that very much. Unfortunately, large part of library is built during the time I was still learning D, so some sort of global makeover would be good for it, in my opinion.

> Doing this will help to use DCV as a backend instead of OpenCV.

We'd need _army_ of CV experts to achieve this. :) But I'm up for it. :D

As said, let me sleep this over, and I'll get back to you here.

**Comment by 9il** [comment]
> Don't you agree?

Yes (agree)

**Comment by ljubobratovicrelja** [comment]
Here we are! :) Thank you for the invite!

Closing the issue...

**Comment by ljubobratovicrelja** [comment]
@9il are you handling libmir's code.dlang.org account? How do we transfer dcv package ownership?

**Comment by 9il** [comment]
> @9il are you handling libmir's code.dlang.org account? How do we transfer dcv package ownership?

code.dlang.org does not have ownerships for groups.
You can just
1. transfer it in github
2. change settings for dcv (your_account -> libmir). This will not change an dub ownership for the package.

**Comment by ljubobratovicrelja** [comment]
Tnx. It's done.

**Comment by 9il** [comment]
https://twitter.com/libmir/status/797803795904417793
We also have a group at gitter https://gitter.im/libmir/public

**Comment by 9il** [comment]
Thank you!
