### ISSUE TITLE
License

### ISSUE THREAD

**Issue by 9il** [libmir/dcv#95]
New ndslice and algorithms will have BSD-3 license like numpy, OpenBLAS and OpenCV
You may want to change DCV license too

**Comment by ljubobratovicrelja** [comment]
> You may want to change DCV license too

I suppose we could do this. Whats the difference, btw? More constraining, less free?

**Comment by 9il** [comment]
> I suppose we could do this. Whats the difference, btw? More constraining, less free?

Main constraint that the copyright should be included, plus authors name protection

**Comment by ljubobratovicrelja** [comment]
> Main constraint that the copyright should be included, plus authors name protection

Yeah I thought so. Sounds legit, vote me in for this change.
