### ISSUE TITLE
Can travis download precompiled C libs from somewhere?

### ISSUE THREAD

**Issue by 9il** [libmir/dcv#96]

**Comment by ljubobratovicrelja** [comment]
I tried this before, but failed for some reason, can't remember why exactly. But you're right this must be done. Test time is way too long...

**Comment by wilzbach** [comment]
@ljubobratovicrelja 
a) just compile them for yourself and store them somewhere
b) use the [caching](https://docs.travis-ci.com/user/caching/) feature at Travis

**Comment by ljubobratovicrelja** [comment]
> use the caching feature at Travis

Awesome, thanks!
